version: '3.9'
services:
  points-farmer:
    container_name: points-farmer-postgres-container
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5444:5432"
    volumes:
      - ./docker-volumes/postgres-points-farmer-volume:/var/lib/postgresql/data
    networks:
      - backend
      
  redis:
    container_name: twitter-points-farmer-redis-container
    image: redis:alpine
    ports:
      - 6379:6379 
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data

networks:
  backend:
    name: backend
